export const SRT_SITUATIONS: string[] = [
  // PERSONAL CHALLENGES (20)
  "You are on your last SSB attempt and fall sick the night before the final interview. You...",
  "You have worked hard for an exam but fail by 2 marks. You...",
  "Your best friend gets selected for a course you both applied for but you did not. You...",
  "You discover just before an important presentation that your preparation has a major error. You...",
  "You are accused of cheating in an exam you did not cheat in. You...",
  "Your father wants you to join the family business but your dream is to join the Armed Forces. You...",
  "You are injured during a training run with 2km still remaining. Your team needs every member to finish. You...",
  "You have been working on a project for months and your senior takes credit for it. You...",
  "You fail your fitness test by a small margin after months of preparation. You...",
  "During an important group task you go blank and cannot contribute anything useful. You...",
  "You receive news of a family emergency on the day of your most important exam. You...",
  "You are repeatedly overlooked for promotion despite strong performance. You...",
  "Your close friend borrows money and refuses to return it when you need it urgently. You...",
  "You realise mid-way through a task that you have been working on the wrong objective. You...",
  "You are wrongly blamed by your senior for a mistake made by your team. You...",
  "You have a conflict between attending a family function and an important duty. You...",
  "You are selected for a prestigious posting but it means leaving your ailing parent alone. You...",
  "You discover you have been spreading incorrect information unknowingly for weeks. You...",
  "Your mentor who guided you throughout your career suddenly turns against you. You...",
  "You are exhausted after 3 days of continuous operations with no sleep. You...",

  // LEADERSHIP AND TEAM (20)
  "You are leading a team and one member consistently arrives late affecting group performance. You...",
  "Your team is demoralised after failing an important exercise. You are the leader. You...",
  "Two strong members of your team are in personal conflict affecting the whole group. You...",
  "You are assigned a team for a critical mission but realise two members are unfit for it. You...",
  "Your team disagrees with your decision during a time-critical operation. You...",
  "A junior team member has a better idea than you during an important task. You...",
  "Your entire team wants to take a shortcut that compromises the quality of the mission. You...",
  "You are new to a team and the existing members resist your leadership. You...",
  "One team member is doing all the work while others are free-riding. You...",
  "Your team is about to miss a critical deadline due to poor coordination. You...",
  "A key team member quits just before an important operation. You...",
  "Your team achieves success but one member claims all the credit. You...",
  "You are leading a patrol and your team members start panicking in a difficult situation. You...",
  "A senior member of your team undermines your authority in front of others. You...",
  "Your team has limited resources for a task that requires double the available amount. You...",
  "Two sub-teams under you are competing instead of cooperating on a joint mission. You...",
  "A team member reveals confidential information to outsiders. You...",
  "Your junior makes a serious mistake that jeopardises the entire mission. You...",
  "You must choose one of two equally qualified candidates for a dangerous assignment. You...",
  "Your team succeeds but you know it was due to luck rather than good planning. You...",

  // EMERGENCY AND CRISIS (20)
  "You witness a road accident with multiple injured victims and you are the first on the scene. You...",
  "A fire breaks out in a building and you can see people trapped on upper floors. You...",
  "You are on a trek when a team member falls and breaks their leg 10km from help. You...",
  "During a river crossing your team member is swept away by the current. You...",
  "You witness a person being attacked in a public place. You are alone and outnumbered. You...",
  "A flood traps your patrol team in a remote area with no communication. You...",
  "Your vehicle breaks down in a hostile area at night. You...",
  "A team member has an allergic reaction during a field exercise and is going into shock. You...",
  "You are the senior-most person present when a serious accident occurs at your unit. You...",
  "A civilian approaches your post in distress claiming their village is under attack. You...",
  "Your base camp catches fire during a night exercise. You...",
  "A young child falls into a well in a village you are passing through. You...",
  "Your aircraft has a technical emergency and you must make an emergency landing. You...",
  "A riot breaks out in a town where your unit is posted. Civilians are at risk. You...",
  "Your boat capsizes during a river crossing exercise with 6 personnel. You...",
  "A bomb threat is called in to a public building you are responsible for. You...",
  "A disease outbreak affects multiple personnel in your unit simultaneously. You...",
  "Your communication equipment fails during a critical operation in hostile territory. You...",
  "A landslide blocks the only road to your forward post with supplies running out. You...",
  "You discover a suspicious package near a crowded civilian area. You...",

  // MORAL AND ETHICAL DILEMMAS (20)
  "You witness a senior officer accepting a bribe from a contractor. You...",
  "Your friend asks you to lie to cover for an absence that was actually a disciplinary violation. You...",
  "You find a wallet with a large sum of money and no identification inside. You...",
  "A fellow cadet is cheating in a written test that determines promotion. You...",
  "You discover your superior has falsified records to make your unit's performance look better. You...",
  "You are asked to sign off on a safety report you know contains inaccuracies. You...",
  "A civilian offers you a gift after you help them during an emergency. You...",
  "Your friend who is also your subordinate is performing poorly but is very popular. You...",
  "You overhear a conversation suggesting a fellow officer is involved in illegal activity. You...",
  "You are pressured by seniors to participate in something you believe is unethical. You...",
  "A colleague shares confidential information with you that could help your career. You...",
  "You see a colleague stealing equipment from the unit store. He is your close friend. You...",
  "You are asked to give a false statement to protect a senior who made an error. You...",
  "A vendor offers you a personal benefit to select their product in a procurement process. You...",
  "You discover your unit has been misusing funds allocated for welfare of junior soldiers. You...",
  "You are asked to suppress a complaint made by a junior soldier against a senior. You...",
  "A close friend asks you to help them cheat on a medical fitness test. You...",
  "You witness religious discrimination against a fellow soldier in your unit. You...",
  "Your superior takes a decision you know is wrong but insists you follow it without question. You...",
  "You are offered a position that you know was meant for a more deserving colleague. You...",

  // INTERPERSONAL AND SOCIAL (20)
  "A clerk demands a bribe to process your legitimate paperwork quickly. You...",
  "Your girlfriend/boyfriend's family opposes your relationship due to your career choice. You...",
  "A local politician tries to interfere in your unit's operations using his influence. You...",
  "You are posted to a remote area and your family is unhappy with the relocation. You...",
  "A journalist approaches you asking for sensitive information about your unit. You...",
  "A senior officer shows clear favoritism towards certain cadets in your batch. You...",
  "You are the only person from your background in a unit where others share a different regional identity. You...",
  "A villager near your post is spreading false rumors about your unit's conduct. You...",
  "A cadet in your batch is being bullied by seniors. You witness it happening. You...",
  "Your parents are pressuring you to get married but you want to focus on your career first. You...",
  "A person on the street collapses in front of you and bystanders refuse to help. You...",
  "You are in uniform and witness a group of youth vandalising public property. You...",
  "A senior at a social function makes an inappropriate remark about your community. You...",
  "You find out that a colleague has been spreading false rumors about you. You...",
  "Your neighbour's house catches fire in the middle of the night. You...",
  "You see a group of students being misled by someone spreading anti-national propaganda. You...",
  "A stranger approaches you at the railway station claiming to be in danger and needing help. You...",
  "You are travelling in a train and witness eve-teasing of a fellow passenger. You...",
  "A local youth comes to you wanting guidance on joining the Armed Forces. You...",
  "You receive an anonymous tip about a potential security threat at a public event. You...",

  // OPERATIONAL AND TRAINING (20)
  "You are on a night patrol and one of your team members falls asleep on duty. You...",
  "Your unit is given an impossible deadline for completing a fortification task. You...",
  "During a field exercise your map and compass are lost. You are deep in unfamiliar terrain. You...",
  "You are given command of a post with very low morale among the soldiers. You...",
  "A new piece of critical equipment arrives but nobody in your unit knows how to operate it. You...",
  "Your ammunition runs short during a live firing exercise. You...",
  "You are ordered to complete a mission you believe has a significant risk to your team. You...",
  "During a training exercise you discover a real security threat that was not part of the script. You...",
  "Your unit must complete a 30km march in extreme heat with several members showing signs of fatigue. You...",
  "You are given charge of organising a major event with half the budget required. You...",
  "Your senior officer is unavailable and you must make an urgent operational decision alone. You...",
  "The rations for your patrol are damaged and inedible with 3 days remaining in the field. You...",
  "You are asked to train a batch of recruits but have never trained anyone before. You...",
  "Your unit vehicle breaks down during a time-critical supply mission. You...",
  "You receive conflicting orders from two senior officers about the same operation. You...",
  "Your unit is inspected and found to be below standards. You are the duty officer. You...",
  "During a joint exercise a misunderstanding with a foreign unit creates a tense standoff. You...",
  "You realise mid-mission that the intelligence briefing you were given was incorrect. You...",
  "A soldier under your command refuses to follow an order during a critical operation. You...",
  "Your unit is the last line of defence and you are outnumbered three to one. You...",
];

export const SRT_CATEGORIES = [
  "Personal Challenges",
  "Leadership and Team",
  "Emergency and Crisis",
  "Moral and Ethical Dilemmas",
  "Interpersonal and Social",
  "Operational and Training",
] as const;

export type SrtCategory = (typeof SRT_CATEGORIES)[number];

export const SRT_CATEGORY_RANGES: Record<SrtCategory, [number, number]> = {
  "Personal Challenges":       [0, 19],
  "Leadership and Team":       [20, 39],
  "Emergency and Crisis":      [40, 59],
  "Moral and Ethical Dilemmas":[60, 79],
  "Interpersonal and Social":  [80, 99],
  "Operational and Training":  [100, 119],
};
