/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard.index'
import { Route as LeaderboardWatRouteImport } from './routes/leaderboard.wat'
import { Route as LeaderboardSrtRouteImport } from './routes/leaderboard.srt'
import { Route as LeaderboardGlobalRouteImport } from './routes/leaderboard.global'
import { Route as TestsWatIndexRouteImport } from './routes/tests.wat.index'
import { Route as TestsSrtIndexRouteImport } from './routes/tests.srt.index'
import { Route as TestsWatPracticeRouteImport } from './routes/tests.wat.practice'
import { Route as TestsSrtPracticeRouteImport } from './routes/tests.srt.practice'
import { Route as TestsWatFullTestRouteImport } from './routes/tests.wat.full.test'
import { Route as TestsWatFullSetupRouteImport } from './routes/tests.wat.full.setup'
import { Route as TestsWatFullResultsRouteImport } from './routes/tests.wat.full.results'
import { Route as TestsWatFullInstructionsRouteImport } from './routes/tests.wat.full.instructions'
import { Route as TestsSrtFullTestRouteImport } from './routes/tests.srt.full.test'
import { Route as TestsSrtFullSetupRouteImport } from './routes/tests.srt.full.setup'
import { Route as TestsSrtFullResultsRouteImport } from './routes/tests.srt.full.results'
import { Route as TestsSrtFullInstructionsRouteImport } from './routes/tests.srt.full.instructions'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestsRoute,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeaderboardRoute,
} as any)
const LeaderboardWatRoute = LeaderboardWatRouteImport.update({
  id: '/wat',
  path: '/wat',
  getParentRoute: () => LeaderboardRoute,
} as any)
const LeaderboardSrtRoute = LeaderboardSrtRouteImport.update({
  id: '/srt',
  path: '/srt',
  getParentRoute: () => LeaderboardRoute,
} as any)
const LeaderboardGlobalRoute = LeaderboardGlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => LeaderboardRoute,
} as any)
const TestsWatIndexRoute = TestsWatIndexRouteImport.update({
  id: '/wat/',
  path: '/wat/',
  getParentRoute: () => TestsRoute,
} as any)
const TestsSrtIndexRoute = TestsSrtIndexRouteImport.update({
  id: '/srt/',
  path: '/srt/',
  getParentRoute: () => TestsRoute,
} as any)
const TestsWatPracticeRoute = TestsWatPracticeRouteImport.update({
  id: '/wat/practice',
  path: '/wat/practice',
  getParentRoute: () => TestsRoute,
} as any)
const TestsSrtPracticeRoute = TestsSrtPracticeRouteImport.update({
  id: '/srt/practice',
  path: '/srt/practice',
  getParentRoute: () => TestsRoute,
} as any)
const TestsWatFullTestRoute = TestsWatFullTestRouteImport.update({
  id: '/wat/full/test',
  path: '/wat/full/test',
  getParentRoute: () => TestsRoute,
} as any)
const TestsWatFullSetupRoute = TestsWatFullSetupRouteImport.update({
  id: '/wat/full/setup',
  path: '/wat/full/setup',
  getParentRoute: () => TestsRoute,
} as any)
const TestsWatFullResultsRoute = TestsWatFullResultsRouteImport.update({
  id: '/wat/full/results',
  path: '/wat/full/results',
  getParentRoute: () => TestsRoute,
} as any)
const TestsWatFullInstructionsRoute =
  TestsWatFullInstructionsRouteImport.update({
    id: '/wat/full/instructions',
    path: '/wat/full/instructions',
    getParentRoute: () => TestsRoute,
  } as any)
const TestsSrtFullTestRoute = TestsSrtFullTestRouteImport.update({
  id: '/srt/full/test',
  path: '/srt/full/test',
  getParentRoute: () => TestsRoute,
} as any)
const TestsSrtFullSetupRoute = TestsSrtFullSetupRouteImport.update({
  id: '/srt/full/setup',
  path: '/srt/full/setup',
  getParentRoute: () => TestsRoute,
} as any)
const TestsSrtFullResultsRoute = TestsSrtFullResultsRouteImport.update({
  id: '/srt/full/results',
  path: '/srt/full/results',
  getParentRoute: () => TestsRoute,
} as any)
const TestsSrtFullInstructionsRoute =
  TestsSrtFullInstructionsRouteImport.update({
    id: '/srt/full/instructions',
    path: '/srt/full/instructions',
    getParentRoute: () => TestsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/leaderboard/global': typeof LeaderboardGlobalRoute
  '/leaderboard/srt': typeof LeaderboardSrtRoute
  '/leaderboard/wat': typeof LeaderboardWatRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/tests/srt/practice': typeof TestsSrtPracticeRoute
  '/tests/wat/practice': typeof TestsWatPracticeRoute
  '/tests/srt/': typeof TestsSrtIndexRoute
  '/tests/wat/': typeof TestsWatIndexRoute
  '/tests/srt/full/instructions': typeof TestsSrtFullInstructionsRoute
  '/tests/srt/full/results': typeof TestsSrtFullResultsRoute
  '/tests/srt/full/setup': typeof TestsSrtFullSetupRoute
  '/tests/srt/full/test': typeof TestsSrtFullTestRoute
  '/tests/wat/full/instructions': typeof TestsWatFullInstructionsRoute
  '/tests/wat/full/results': typeof TestsWatFullResultsRoute
  '/tests/wat/full/setup': typeof TestsWatFullSetupRoute
  '/tests/wat/full/test': typeof TestsWatFullTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard/global': typeof LeaderboardGlobalRoute
  '/leaderboard/srt': typeof LeaderboardSrtRoute
  '/leaderboard/wat': typeof LeaderboardWatRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/tests': typeof TestsIndexRoute
  '/tests/srt/practice': typeof TestsSrtPracticeRoute
  '/tests/wat/practice': typeof TestsWatPracticeRoute
  '/tests/srt': typeof TestsSrtIndexRoute
  '/tests/wat': typeof TestsWatIndexRoute
  '/tests/srt/full/instructions': typeof TestsSrtFullInstructionsRoute
  '/tests/srt/full/results': typeof TestsSrtFullResultsRoute
  '/tests/srt/full/setup': typeof TestsSrtFullSetupRoute
  '/tests/srt/full/test': typeof TestsSrtFullTestRoute
  '/tests/wat/full/instructions': typeof TestsWatFullInstructionsRoute
  '/tests/wat/full/results': typeof TestsWatFullResultsRoute
  '/tests/wat/full/setup': typeof TestsWatFullSetupRoute
  '/tests/wat/full/test': typeof TestsWatFullTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRouteWithChildren
  '/tests': typeof TestsRouteWithChildren
  '/leaderboard/global': typeof LeaderboardGlobalRoute
  '/leaderboard/srt': typeof LeaderboardSrtRoute
  '/leaderboard/wat': typeof LeaderboardWatRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/tests/srt/practice': typeof TestsSrtPracticeRoute
  '/tests/wat/practice': typeof TestsWatPracticeRoute
  '/tests/srt/': typeof TestsSrtIndexRoute
  '/tests/wat/': typeof TestsWatIndexRoute
  '/tests/srt/full/instructions': typeof TestsSrtFullInstructionsRoute
  '/tests/srt/full/results': typeof TestsSrtFullResultsRoute
  '/tests/srt/full/setup': typeof TestsSrtFullSetupRoute
  '/tests/srt/full/test': typeof TestsSrtFullTestRoute
  '/tests/wat/full/instructions': typeof TestsWatFullInstructionsRoute
  '/tests/wat/full/results': typeof TestsWatFullResultsRoute
  '/tests/wat/full/setup': typeof TestsWatFullSetupRoute
  '/tests/wat/full/test': typeof TestsWatFullTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/tests'
    | '/leaderboard/global'
    | '/leaderboard/srt'
    | '/leaderboard/wat'
    | '/leaderboard/'
    | '/tests/'
    | '/tests/srt/practice'
    | '/tests/wat/practice'
    | '/tests/srt/'
    | '/tests/wat/'
    | '/tests/srt/full/instructions'
    | '/tests/srt/full/results'
    | '/tests/srt/full/setup'
    | '/tests/srt/full/test'
    | '/tests/wat/full/instructions'
    | '/tests/wat/full/results'
    | '/tests/wat/full/setup'
    | '/tests/wat/full/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard/global'
    | '/leaderboard/srt'
    | '/leaderboard/wat'
    | '/leaderboard'
    | '/tests'
    | '/tests/srt/practice'
    | '/tests/wat/practice'
    | '/tests/srt'
    | '/tests/wat'
    | '/tests/srt/full/instructions'
    | '/tests/srt/full/results'
    | '/tests/srt/full/setup'
    | '/tests/srt/full/test'
    | '/tests/wat/full/instructions'
    | '/tests/wat/full/results'
    | '/tests/wat/full/setup'
    | '/tests/wat/full/test'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/tests'
    | '/leaderboard/global'
    | '/leaderboard/srt'
    | '/leaderboard/wat'
    | '/leaderboard/'
    | '/tests/'
    | '/tests/srt/practice'
    | '/tests/wat/practice'
    | '/tests/srt/'
    | '/tests/wat/'
    | '/tests/srt/full/instructions'
    | '/tests/srt/full/results'
    | '/tests/srt/full/setup'
    | '/tests/srt/full/test'
    | '/tests/wat/full/instructions'
    | '/tests/wat/full/results'
    | '/tests/wat/full/setup'
    | '/tests/wat/full/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRouteWithChildren
  TestsRoute: typeof TestsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof TestsRoute
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof LeaderboardRoute
    }
    '/leaderboard/wat': {
      id: '/leaderboard/wat'
      path: '/wat'
      fullPath: '/leaderboard/wat'
      preLoaderRoute: typeof LeaderboardWatRouteImport
      parentRoute: typeof LeaderboardRoute
    }
    '/leaderboard/srt': {
      id: '/leaderboard/srt'
      path: '/srt'
      fullPath: '/leaderboard/srt'
      preLoaderRoute: typeof LeaderboardSrtRouteImport
      parentRoute: typeof LeaderboardRoute
    }
    '/leaderboard/global': {
      id: '/leaderboard/global'
      path: '/global'
      fullPath: '/leaderboard/global'
      preLoaderRoute: typeof LeaderboardGlobalRouteImport
      parentRoute: typeof LeaderboardRoute
    }
    '/tests/wat/': {
      id: '/tests/wat/'
      path: '/wat'
      fullPath: '/tests/wat/'
      preLoaderRoute: typeof TestsWatIndexRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/srt/': {
      id: '/tests/srt/'
      path: '/srt'
      fullPath: '/tests/srt/'
      preLoaderRoute: typeof TestsSrtIndexRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/wat/practice': {
      id: '/tests/wat/practice'
      path: '/wat/practice'
      fullPath: '/tests/wat/practice'
      preLoaderRoute: typeof TestsWatPracticeRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/srt/practice': {
      id: '/tests/srt/practice'
      path: '/srt/practice'
      fullPath: '/tests/srt/practice'
      preLoaderRoute: typeof TestsSrtPracticeRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/wat/full/test': {
      id: '/tests/wat/full/test'
      path: '/wat/full/test'
      fullPath: '/tests/wat/full/test'
      preLoaderRoute: typeof TestsWatFullTestRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/wat/full/setup': {
      id: '/tests/wat/full/setup'
      path: '/wat/full/setup'
      fullPath: '/tests/wat/full/setup'
      preLoaderRoute: typeof TestsWatFullSetupRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/wat/full/results': {
      id: '/tests/wat/full/results'
      path: '/wat/full/results'
      fullPath: '/tests/wat/full/results'
      preLoaderRoute: typeof TestsWatFullResultsRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/wat/full/instructions': {
      id: '/tests/wat/full/instructions'
      path: '/wat/full/instructions'
      fullPath: '/tests/wat/full/instructions'
      preLoaderRoute: typeof TestsWatFullInstructionsRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/srt/full/test': {
      id: '/tests/srt/full/test'
      path: '/srt/full/test'
      fullPath: '/tests/srt/full/test'
      preLoaderRoute: typeof TestsSrtFullTestRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/srt/full/setup': {
      id: '/tests/srt/full/setup'
      path: '/srt/full/setup'
      fullPath: '/tests/srt/full/setup'
      preLoaderRoute: typeof TestsSrtFullSetupRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/srt/full/results': {
      id: '/tests/srt/full/results'
      path: '/srt/full/results'
      fullPath: '/tests/srt/full/results'
      preLoaderRoute: typeof TestsSrtFullResultsRouteImport
      parentRoute: typeof TestsRoute
    }
    '/tests/srt/full/instructions': {
      id: '/tests/srt/full/instructions'
      path: '/srt/full/instructions'
      fullPath: '/tests/srt/full/instructions'
      preLoaderRoute: typeof TestsSrtFullInstructionsRouteImport
      parentRoute: typeof TestsRoute
    }
  }
}

interface LeaderboardRouteChildren {
  LeaderboardGlobalRoute: typeof LeaderboardGlobalRoute
  LeaderboardSrtRoute: typeof LeaderboardSrtRoute
  LeaderboardWatRoute: typeof LeaderboardWatRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
}

const LeaderboardRouteChildren: LeaderboardRouteChildren = {
  LeaderboardGlobalRoute: LeaderboardGlobalRoute,
  LeaderboardSrtRoute: LeaderboardSrtRoute,
  LeaderboardWatRoute: LeaderboardWatRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
}

const LeaderboardRouteWithChildren = LeaderboardRoute._addFileChildren(
  LeaderboardRouteChildren,
)

interface TestsRouteChildren {
  TestsIndexRoute: typeof TestsIndexRoute
  TestsSrtPracticeRoute: typeof TestsSrtPracticeRoute
  TestsWatPracticeRoute: typeof TestsWatPracticeRoute
  TestsSrtIndexRoute: typeof TestsSrtIndexRoute
  TestsWatIndexRoute: typeof TestsWatIndexRoute
  TestsSrtFullInstructionsRoute: typeof TestsSrtFullInstructionsRoute
  TestsSrtFullResultsRoute: typeof TestsSrtFullResultsRoute
  TestsSrtFullSetupRoute: typeof TestsSrtFullSetupRoute
  TestsSrtFullTestRoute: typeof TestsSrtFullTestRoute
  TestsWatFullInstructionsRoute: typeof TestsWatFullInstructionsRoute
  TestsWatFullResultsRoute: typeof TestsWatFullResultsRoute
  TestsWatFullSetupRoute: typeof TestsWatFullSetupRoute
  TestsWatFullTestRoute: typeof TestsWatFullTestRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsIndexRoute: TestsIndexRoute,
  TestsSrtPracticeRoute: TestsSrtPracticeRoute,
  TestsWatPracticeRoute: TestsWatPracticeRoute,
  TestsSrtIndexRoute: TestsSrtIndexRoute,
  TestsWatIndexRoute: TestsWatIndexRoute,
  TestsSrtFullInstructionsRoute: TestsSrtFullInstructionsRoute,
  TestsSrtFullResultsRoute: TestsSrtFullResultsRoute,
  TestsSrtFullSetupRoute: TestsSrtFullSetupRoute,
  TestsSrtFullTestRoute: TestsSrtFullTestRoute,
  TestsWatFullInstructionsRoute: TestsWatFullInstructionsRoute,
  TestsWatFullResultsRoute: TestsWatFullResultsRoute,
  TestsWatFullSetupRoute: TestsWatFullSetupRoute,
  TestsWatFullTestRoute: TestsWatFullTestRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRouteWithChildren,
  TestsRoute: TestsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
